"""remove unique constraint e renomeia coluna

Revision ID: 2224b5e4cf9f
Revises: a675c636c627
Create Date: 2025-08-11 19:33:39.125609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2224b5e4cf9f'
down_revision: Union[str, Sequence[str], None] = 'a675c636c627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalities', sa.Column('modality_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('modality_name_unique'), 'modalities', type_='unique')
    op.drop_column('modalities', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalities', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('modality_name_unique'), 'modalities', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('modalities', 'modality_name')
    # ### end Alembic commands ###
