"""tabela modalities e user_modalities

Revision ID: 305805ea388e
Revises: 34ca8db5aa71
Create Date: 2025-08-06 15:30:50.437309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305805ea388e'
down_revision: Union[str, Sequence[str], None] = '34ca8db5aa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('jiu_jitsu', 'capoeira', name='fightstyle', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_modalities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'modality_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_modalities')
    op.drop_table('modalities')
    op.execute('DROP TYPE fightstyle')
    # ### end Alembic commands ###
