"""mudando o tipo da modalidade para str

Revision ID: 40399a8eea66
Revises: 305805ea388e
Create Date: 2025-08-06 16:04:15.541414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40399a8eea66'
down_revision: Union[str, Sequence[str], None] = '305805ea388e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modalities', 'name',
               existing_type=postgresql.ENUM('jiu_jitsu', 'capoeira', name='fightstyle'),
               type_=sa.String(),
               existing_nullable=False)
    op.execute('DROP TYPE IF EXISTS fightstyle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE fightstyle AS ENUM ('jiu-jitsu', 'capoeira')")

    op.execute("""
        ALTER TABLE modalities 
        ALTER COLUMN name 
        TYPE fightstyle 
        USING name::fightstyle
    """)
    # ### end Alembic commands ###
