"""adicionando unicidade para o nome da modalidade

Revision ID: af740ece1b01
Revises: 40399a8eea66
Create Date: 2025-08-06 16:31:59.857164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af740ece1b01'
down_revision: Union[str, Sequence[str], None] = '40399a8eea66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('modality_name_unique', 'modalities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modality_name_unique', 'modalities', type_='unique')
    # ### end Alembic commands ###
